M48
; DRILL file {KiCad 7.0.1} date Thu Apr  6 02:47:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-06T02:47:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X1.5043Y-0.7264
X1.7319Y-0.7264
T2
X0.7717Y-0.8425
X1.8661Y-0.5748
X1.8661Y-0.8425
T3
X0.6693Y-0.7087
T0
M30
